### ISSUE TITLE
Warn about CSV download timeout on large datasets

### ISSUE THREAD

**Issue by sawyerball** [cs481-ekh/s23-wildfire-wizards#105]
User Story #104 

Right now, when large datasets are queried, the CSV download will timeout. We need to figure out why this is happening as well as prevent it from happening anymore.

For an example, try to download a CSV file with parameters: 
- YEAR: 1992
- STATE: CA
- COUNTY: {blank}

It will find over 10,000 results.

**Comment by ethanraygor** [comment]
Implemennted this task.
{t:20}
